import pandas as pd
from models import Empleado, db
from datetime import datetime
from app import app
from werkzeug.security import generate_password_hash  # Generated by Copilot

with app.app_context():
    df = pd.read_excel("empleados.xlsx")

    # Limpiar y normalizar nombres de columnas
    df.columns = [col.strip().lower().replace(' ', '_') for col in df.columns]  # Generated by Copilot

    print("📋 Columnas normalizadas:", df.columns.tolist())

    df["fecha_ingreso"] = pd.to_datetime(df["fecha_ingreso"], errors="coerce").dt.date

    print(df.columns.tolist())

    for _, row in df.iterrows():
        if not Empleado.query.filter_by(email=row['email']).first():
            import secrets  # Generar contraseñas seguras
            contrasena_segura = secrets.token_urlsafe(12)  # Generar una contraseña aleatoria
            nuevo_empleado = Empleado(
            nombre=row['nombre'],
            email=row['email'],
            password=generate_password_hash('1234'), 
            fecha_ingreso=row['fecha_ingreso'],
            antiguedad=row['antiguedad'],
            vacaciones=row['vacaciones'],
            pendientes=row['pendientes'],
            sueldo=row['sueldo'],
            puesto=row['puesto'],
            sanciones=row['sanciones'],
            referencias=row['referencias'],
            trayectoria=row['trayectoria'],
            cursos=row['cursos']
            )
            db.session.add(nuevo_empleado)
            db.session.commit()
            print(f'Empleado agregado: {nuevo_empleado.nombre} - {nuevo_empleado.email} - {nuevo_empleado.referencias}')  # Generated by Copilot
            
        

    